# Generated by Django 3.2.7 on 2021-10-31 14:33

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20211031_1456'),
        ('users', '0007_auto_20211031_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=models.CharField(choices=[('uploader', 'uploader'), ('student', 'student')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.studentstage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='avatars/default.jpg', upload_to='avatars'),
        ),
    ]
