# Generated by Django 3.1.3 on 2021-10-31 16:56

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211031_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='/staticfiles/default.jpg', upload_to='avatars'),
        ),
    ]
