# Generated by Django 3.1.3 on 2021-12-02 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['complete']},
        ),
        migrations.AddField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
