# Generated by Django 3.1.3 on 2022-01-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20211202_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
