# Generated by Django 3.1.3 on 2021-09-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lectures_vote_count'),
        ('polls', '0006_auto_20210921_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturevote',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.lectures'),
        ),
    ]
