# Generated by Django 3.2.7 on 2022-07-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_auto_20220727_2151'),
        ('polls', '0013_auto_20211201_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturevote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturevote',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.lectures'),
        ),
    ]
