# Generated by Django 3.2.7 on 2022-07-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_remove_lectures_vote_count'),
        ('polls', '0014_auto_20220727_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturevote',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturesv', to='lectures.lectures'),
        ),
    ]
