# Generated by Django 3.1.3 on 2021-09-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('lectures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.lectures')),
            ],
        ),
        migrations.AddField(
            model_name='lectures',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.studentstage'),
        ),
    ]
