# Generated by Django 3.1.3 on 2021-09-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
