# Generated by Django 3.2.7 on 2022-07-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_auto_20220727_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='vote_count',
        ),
    ]
