# Generated by Django 3.2.7 on 2022-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_remove_lectures_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
